'use client'

import Image from 'next/image'
import Link from 'next/link'
import { use, useMemo, useState } from 'react'
import { ArrowLeft, Check, MessageCircle, Minus, Plus, ShoppingBag, Sparkles } from 'lucide-react'

const catalog = [
  { slug: 'luminous-silk-radiance-serum', name: 'Luminous Silk Radiance Serum', category: 'SKINCARE', price: 48, image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=85', description: 'Infused with 24K micronized rose gold and botanical squalane.', details: 'A luminous, featherweight serum that cushions skin in botanical oils and a veil of soft radiance.' },
  { slug: 'rose-petal-velvet-matte-lipstick', name: 'Rose Petal Velvet Matte Lipstick', category: 'LIPS', price: 32, image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=1200&q=85', description: 'A weightless velvet formula infused with camellia seed extract.', details: 'A refined matte lip color with comfortable, long-wearing pigment and a petal-soft finish.' },
  { slug: 'desert-sunset-eyeshadow-palette', name: 'Desert Sunset Eyeshadow Palette', category: 'EYES', price: 56, image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=1200&q=85', description: 'Twelve artisanal shades ranging from warm terracotta mattes to dimensional rose gold.', details: 'Twelve buildable shades inspired by desert dusk, designed for effortless day-to-evening artistry.' },
  { slug: 'golden-hour-glow-facial-mist', name: 'Golden Hour Glow Facial Mist', category: 'SKINCARE', price: 28, image: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=1200&q=85', description: 'An ultra-fine mist infused with Moroccan Damask rosewater and niacinamide.', details: 'A refreshing botanical veil that softens, hydrates, and restores a dewy finish throughout the day.' },
  { slug: 'celestial-rose-hydrating-cream', name: 'Celestial Rose Hydrating Cream', category: 'SKINCARE', price: 64, image: 'https://images.unsplash.com/photo-1611930021553-1e4c3e4b2b1f?auto=format&fit=crop&w=1200&q=85', description: 'A decadent whipped cloud cream that melts onto skin with peptides and squalane.', details: 'A cloud-soft moisturizer with cold-pressed rose, peptides, and nourishing squalane.' },
  { slug: 'sheer-nectar-peptide-lip-glaze', name: 'Sheer Nectar Peptide Lip Glaze', category: 'LIPS', price: 24, image: 'https://images.unsplash.com/photo-1586495778362-9e4d6f2f9c00?auto=format&fit=crop&w=1200&q=85', description: 'Non-sticky, mirror-shine treatment enriched with multi-peptides and jojoba butter.', details: 'A sheer conditioning glaze that cushions lips with reflective shine and soft botanical comfort.' },
]

export default function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = use(params)
  const product = catalog.find((item) => item.slug === slug) ?? catalog[0]
  const [quantity, setQuantity] = useState(1)
  const total = useMemo(() => product.price * quantity, [product.price, quantity])
  const order = () => window.open(`https://wa.me/${process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '15551234567'}?text=${encodeURIComponent(`Hello, I would like to order ${quantity} × ${product.name} for $${total.toFixed(2)}.`)}`, '_blank')

  return <main className="min-h-screen bg-[#fbf8f5] text-[#19151b]"><header className="border-b border-[#eadfdb] bg-[#fffdfb] px-5 md:px-10"><div className="mx-auto flex h-[72px] max-w-[1180px] items-center justify-between"><Link href="/" className="font-serif text-xl">NOOR <i className="text-[#b54358]">Store</i><small className="ml-2 font-sans text-[8px] tracking-[.25em] text-[#8c7b7c]">HAUTE BEAUTÉ</small></Link><Link href="/" className="text-xs text-[#8a7d7d]"><ArrowLeft className="mr-2 inline" size={14}/> Back to catalog</Link></div></header><div className="mx-auto grid max-w-[1180px] gap-12 px-5 py-12 md:grid-cols-2 md:px-10 md:py-20"><div className="relative"><Image src={product.image} alt={product.name} width={1200} height={1200} className="h-[520px] w-full rounded-2xl object-cover shadow-xl"/><span className="absolute left-5 top-5 rounded-full bg-white px-4 py-2 text-[10px] tracking-widest text-[#a5344d]">{product.category}</span></div><div className="flex flex-col justify-center"><p className="text-[10px] tracking-[.25em] text-[#a5344d]">NOOR FORMULATION 0{product.category === 'SKINCARE' ? 1 : 2}</p><h1 className="mt-4 max-w-lg font-serif text-5xl leading-tight md:text-6xl">{product.name}</h1><p className="mt-5 text-sm leading-7 text-[#8a7d7d]">{product.details}</p><div className="mt-7 flex items-center gap-4"><span className="font-serif text-3xl text-[#a5344d]">${product.price.toFixed(2)}</span><span className="text-xs text-[#8a7d7d]">Complimentary delivery over $75</span></div><div className="mt-8 flex items-center gap-4"><div className="flex items-center gap-4 rounded-full border border-[#ead1d3] bg-white px-4 py-3"><button aria-label="Decrease quantity" onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus size={14}/></button><span className="min-w-5 text-center text-sm">{quantity}</span><button aria-label="Increase quantity" onClick={() => setQuantity(quantity + 1)}><Plus size={14}/></button></div><button onClick={order} className="flex-1 rounded-full bg-[#b54358] px-6 py-4 text-sm text-white shadow-lg"><MessageCircle className="mr-2 inline" size={16}/> Order via WhatsApp</button></div><div className="mt-9 grid gap-3 border-t border-[#eadfdb] pt-6 text-xs text-[#625558]"><p><Check className="mr-2 inline text-[#b54358]" size={15}/> Clean, cruelty-free formulation</p><p><Sparkles className="mr-2 inline text-[#b54358]" size={15}/> Hand-finished in small batches</p><p><ShoppingBag className="mr-2 inline text-[#b54358]" size={15}/> Gift-ready NOOR packaging</p></div></div></div></main>
}
